apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: cp4s-deployer-run
spec:
  timeouts:
    pipeline: 7h0m0s
  pipelineRef:
    name: cp4s-deploy
  params:
    - name: namespace
      value: "cp4s"
    - name: ibm-entitlement-key
      value: "false"
    - name: cp4s-version
      value: "1.10"
    - name: verify-url
      value: ""
    - name: verify-client-id
      value: ""
    - name: verify-client-secret
      value: ""
    - name: verify-admin-email
      value: ""
  workspaces:
    - name: cp4s-ws
      volumeClaimTemplate:
        metadata:
          creationTimestamp: null
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
          volumeMode: Filesystem
        status: {}
    